packages:
  - packages/*

minimumReleaseAge: 4320

onlyBuiltDependencies:
  - esbuild
  - netlify-cli
  - sharp

overrides:
  "@eslint/plugin-kit@<0.3.4": ">=0.3.4"
  "@metamask/sdk-communication-layer@>=0.16.0 <=0.33.0": ">=0.33.1"
  "@metamask/sdk@>=0.16.0 <=0.33.0": ">=0.33.1"
  axios@<0.30.0: ">=0.30.0"
  axios@<0.30.2: ">=0.30.2"
  axios@>=0.8.1 <0.28.0: ">=0.28.0"
  axios@>=1.0.0 <1.12.0: ">=1.12.0"
  axios@>=1.0.0 <1.8.2: ">=1.8.2"
  bufferutil: 4.0.9
  cross-spawn@>=7.0.0 <7.0.5: ">=7.0.5"
  ejs@<3.1.10: ">=3.1.10"
  esbuild@<=0.24.2: ">=0.25.0"
  fastify@=4.29.0: ">=4.29.1"
  glob@>=11.0.0 <11.1.0: ">=11.1.0"
  ipx@>=2.0.0-0 <2.1.1: ">=2.1.1"
  js-yaml@>=4.0.0 <4.1.1: ">=4.1.1"
  semver@>=7.0.0 <7.5.2: ">=7.5.2"
  tmp@<=0.2.3: ">=0.2.4"
