packages:
  - packages/*

overrides:
  '@babel/runtime@<7.26.10': '>=7.26.10'
  '@eslint/plugin-kit@<0.3.4': '>=0.3.4'
  '@metamask/sdk-communication-layer@>=0.16.0 <=0.33.0': '>=0.33.1'
  '@metamask/sdk@>=0.16.0 <=0.33.0': '>=0.33.1'
  axios@<0.30.0: '>=0.30.0'
  axios@<0.30.2: '>=0.30.2'
  axios@>=0.8.1 <0.28.0: '>=0.28.0'
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
  cross-spawn@>=7.0.0 <7.0.5: '>=7.0.5'
  ejs@<3.1.10: '>=3.1.10'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  glob@>=11.0.0 <11.1.0: '>=11.1.0'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  node-forge@<1.3.2: '>=1.3.2'
  parse-duration@<2.1.3: '>=2.1.3'
  semver@>=7.0.0 <7.5.2: '>=7.5.2'
  tmp@<=0.2.3: '>=0.2.4'
  undici@>=7.0.0 <7.2.3: '>=7.2.3'
  undici@>=7.0.0 <7.5.0: '>=7.5.0'
