import {
  afterAll,
  assert,
  beforeAll,
  clearStore,
  describe,
  test,
} from "matchstick-as";
import { Address, Bytes } from "@graphprotocol/graph-ts";
import { handleAffiliateSell } from "../src/bunny-universe";
import { createAffiliateSellEvent } from "./bunny-universe-utils";

// Tests structure (matchstick-as >=0.5.0)
// https://thegraph.com/docs/en/developer/matchstick/#tests-structure-0-5-0

describe("AffiliateSell entity", () => {
  beforeAll(() => {
    const affiliate = Address.fromString(
      "0x0000000000000000000000000000000000000001",
    );
    const newAffiliateSellEvent = createAffiliateSellEvent(affiliate);
    handleAffiliateSell(newAffiliateSellEvent);
  });

  afterAll(() => {
    clearStore();
  });

  test("AffiliateSell created and stored", () => {
    // Verify entity count
    assert.entityCount("AffiliateSell", 1);

    // The entity ID is generated by: event.transaction.hash.concatI32(event.logIndex.toI32())
    // Default mock event uses txHash: 0xa16081f360e3847006db660bae1c6d1b2e17ec2a and logIndex: 1
    // concatI32(1) appends 4 bytes (little-endian i32) to the hash
    const txHash = Bytes.fromHexString(
      "0xa16081f360e3847006db660bae1c6d1b2e17ec2a",
    );
    const expectedId = txHash.concatI32(1);

    assert.fieldEquals(
      "AffiliateSell",
      expectedId.toHexString(),
      "affiliate",
      "0x0000000000000000000000000000000000000001",
    );
  });
});
